version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - UPLOAD_DIR=/app/uploads
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
